= Salespoint Framework - Technical Reference
Andreas Zaschka; Paul Henke; Oliver Gierke;
:source-base: ../../main/java/org/salespointframework
:source-base-test: ../../test/java/org/salespointframework
:toc:
:revnumber: {version}
:revdate: {localdate}

[[preface]]
= Preface

[preface]
[[preface.introduction]]
== Introduction
The Salespoint Framework is intended to minimize developing effort of point-of-sale applications. Salespoint 2010 users complainted about complexity, missing features and bugs. Thus, the decision was made to re-design and re-implement the framework from scratch. In 2013 some parts again were re-implemented with components of the spring project. Our development goal was an easy-to-use framework primarily targeted for educational purposes. As such Salespoint 5 is not tailored to any specific application, but designed with a wide area of applications in mind.

Models and design patterns employed in Salespoint 5 are inspired by _Enterprise Patterns and MDA_ <<epam>>. An overview of the functionality of the new features in Salespoint 5 are detailed in this document. We would like to thank all Salespoint users who submitted their feedback and encourage future users of Salespoint 5 to do the same.

[preface]
[[preface.typographic-conventions]]
== Typographic Conventions
Two typographic conventions are employed throughout this document to highlight specific phrases. The following paragraphs describe when and why these highlightings are used:

`Keywords`

The monospace font is used to denote variable names, class names, type names, Java keywords, Java package names and so forth.

_Termini_

Proper names and termini are printed in termini font.

[[architecture]]
= Technical Architecture

* Library and foundation for a Java based web application
* Spring
* Built with Maven
* Reference documentation with Asciidoctor
* A variety of business modules to contain entities and repositories, in some cases even service interfaces
* Spring configuration setup
* Sample projects
** https://github.com/st-tu-dresden/guestbook[Guestbook] - A sample illustrating the pure tech stack, no Salespoint involved.
** https://github.com/st-tu-dresden/videoshop[Videoshop] - A sample web application built on top of Salespoint.
** https://github.com/st-tu-dresden/kickstart[Kickstart] - Empty template project to build an app on top of Salespoint.

[[architecture.core-concepts]]
== Core concepts
Before we dive into the technical details of Salespoint, let's make sure we understand some core concepts that will help us understand the different modules of the framework a bit better. Each of the <<modules, modules>> consists of a bit of code and the classes can usually be grouped into 3 different buckets: entities and value objects, summarized to <<architecture.core-concepts.ddd.newables, newables>>, repositories and services, summarized to <<architecture.core-concepts.ddd.injectables, injectables>> as well as <<architecture.core-concepts.container-configuration, Spring container configuration and extension code>>. The following sections will cast some light on these kinds of types and their special traits.

[[architecture.core-concepts.ddd.newables]]
=== Entities and value objects

TODO

[[architecture.core-concepts.ddd.injectables]]
=== Repositories, services and controllers

Repositories and services are used ot interact with entities and value objects. Repositories usually abstract data access into an interface that simulates a collection of entities that instances can be added to, or looked up using a parameterized criteria like "all users with a certain lastname like…". As Salespoint is using a relational database as persistence backend it leverages the Java Persistence API (JPA) and <<stack.spring-data-jpa, Spring Data JPA>> to implement repositories.

As repositories abstract a collection of an aggregate root (e.g. an order with it's charge and line items), we usually need a higher level abstraction that exposes a more use-case oriented API: a service. It fulfils a more coarse grained set of operations that might include the interaction with multiple repositories, trigger other services in the system etc.

Repositories, services and controllers are types whose instances are managed by the Spring container. Thus they're never instantiated manually in the application code, except for unit testing purposes. Application code uses dependency injection to access 

[[architecture.core-concepts.container-configuration]]
=== Container configuration and extensions

TODO

[[architecture.maven]]
== Maven

TODO

[[architecture.spring]]
== Spring
In contrast to earlier versions of the Salespoint Framework, Salespoint 5 obeys the MVC pattern. Salespoint 5 can be seen as the Model of an MVC application, no parts of the View or the Controller are implemented in the framework.
Salespoint 5 is designed as basis for development of web applications, using the _Spring Framework_ [6] to implement Views and Controllers. To further ease the development, Salespoint 5 includes property editors to convert string based representations to Salespoint 5 identifier types. Furthermore, JSP tags to check, if a user is logged in and if a user has a certain capability are included in the framework. Read more about this in <<stack.spring>>.

As a big new approach in development with JPA, the Spring Framework with its repository interfaces can make the work very fast, clean and easy. The Crudrepository provides the basic methods for working with the database (CRUD stands for Create, Read, Update and Delete).

[[architecture.configuration]]
==	Configuration of Salespoint {version}

The configuration for an application can be modified on the application class in the root package (e.g.  videoshop.Videoshop for the videoshop project). Methods, annotated with `@Configuration`, will be scanned at the beginning of the deployment on the application server (in this case Spring Boot). This configuration files will tell the application server the settings for the application. By overriding the configuration method, you can specify the login behaviour or security functions. For a basic login strategy the videoshop is a good start. There you can see, that with authorizeRequests() an authorization will be set. Following by matchers, you can specify the pages, this authorization is made on. Further, you can easily set an login page with formLogin() and the path to the login page with loginProcessingUrl("/login"). Analogue the logout settings works like login system.

[[stack]]
= Technical Stack

[[stack.spring-boot]]
== Spring Boot

Rapid application development framework based on Spring (see below).

- http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle[Reference documentation]
- https://spring.io/guides[Getting started guides]
- http://projects.spring.io/spring-boot[Project home]

[[stack.spring]]
== Spring 4

The de-facto standard Java application framework.

- https://spring.io/guides[Getting started guides]
- http://projects.spring.io/spring-framework[Project home]

[[stack.spring.core-concepts]]
=== Core concepts

TODO

[[stack.spring.core-concepts.dependency-injection]]
==== Dependency injection

TODO

[[stack.spring.core-concepts.components]]
==== Components and component scanning

TODO

[[stack.spring-data-jpa]]
== Spring Data JPA

Spring module to easily build data acess layers using JPA 2.1 (Java Persistence API).

- https://spring.io/guides?filter=jpa[Getting started guides]
- http://projects.spring.io/spring-data-jpa[Project home]

[[stack.thymeleaf]]
== Thymeleaf

Library to build HTML web views using natural templating.

- https://spring.io/guides/gs/serving-web-content[Getting stared guide]
- http://www.thymeleaf.org/doc/usingthymeleaf.html[Tutorial]

[[stack.joda-money]]
==  JodaMoney
With Salespoint 6.0 money class and its related components were replaced by the Joda-Money [7] project. Prices and other money values are represented as `org.joda.money.Money` or for more precisison as `org.joda.money.BigMoney` objects. Due to the fact, that all representing objects are immutable, all arithmetic functions produce a new instance.

.Example for JodaMoney operations
====
[source, java]
----
Money first = Money.parse(“USD 23.07”);
Money second = Money.parse(“USD 18.07”);
Money sum = first.plus(second);
----
====

Joda-Money also supports `Currency` (see _Example for JodaMoney operations_). A set of loaded currencies is provided by an instance of `CurrencyUnitDataProvider`. But new and funky `CurrencyUnits` can be created to. So with this currencies, money values can be converted from one to another currency.

[[modules]]
= Business modules

[[modules.useraccount]]
== Useraccount
To manage system accounts, Salespoint 5 has a notation of a user in the form of the User interface. Users are managed by the UserAccountManager, who is also an interface. Every user is uniquely identified by a `org.salespointframework.useraccount.UserAccountIdentifier`, which also serves as primary key attribute for the database.

[[modules.useraccount.userrole]]
=== UserRole
`org.salespointframework.useraccount.Role` s in conjunction with authorization tag `hasRole()` can be used to change the appearance of a View, depending on a user’s status. For example, a View for a user having an “administrator” role may display different content, for example delete buttons, than for a user not having that role. Thus, roles allow for flexibility and assist in code reuse, when designing the `View`.

[[modules.useraccount.login]]
=== Login
To reduce code repetition, Salespoint 5 contains code to automate user log in. Using a JSP template, a special login form is generated, which is handled by an interceptor. The interceptor verifies the user password and associates the current session with the user using `<login>` and `<logoff>`. The session is required, because multiple users can be logged on at the same time.

[[modules.useraccount.limitation]]
=== Limitation
Due to the fact, that Salespoint use the `SecurityContext` for authentication, the `UserAccount` cannot be extended. In the background the `org.salespointframework.useraccount.UserAccount` is converted to an instance of `org.springframework.security.core.userdetails.UserDetails`.

If this properties don’t meet all requirements, wrap the `UserAccount` in a new `Entity`. Put all the new features in this new `Entity` and connect this information via a `@OneToOne` relationship with the `UserAccount`.
An Example is the videoshop project.

.Example of a UserAccount extension
====
[source, java]
----
@Entity
public class UserAccountExtension {

	private String string;
	private Integer integer;

	@OneToOne
	private UserAccount userAccount;
}
----
====

[[modules.product]]
== Product
Salespoint 5 is intended as framework for point-of-sale applications. The items for sale are called “products” and represented by instances of class `Product` . To represent different kinds of products, `Product` can be sub-classed. Products are aggregated by `PersistentCatalog` (see Section <<modules.catalog>>).

[[modules.product.identifier]]
=== Product Identifier
Products are supposed to be an abstraction, like an item on display or a picture in a catalog. ProductInstances are used to represent the actual item you get, when you a buy a product. Products are identified using a `ProductIndentifier` , whereas ProductInstances are identified by a SerialNumber. ProductInstances can be thought of as identifiable instances of a certain product, which are identical apart from their SerialNumber.

[[modules.quantity]]
== Quantity
`Quantity` is used to represent amaounts of anything. `Quantity` objects are immutable and the class implements the `Comparable` interface.

=== Attributes of Quantity
* a numerical value -> <<modules.quantity.value>>
* a (meansurement) unit or metric -> <<modules.quantity.metric>>
* a type specifing the rounding of the numerical type -> <<modules.quantity.rounding>>

[[modules.quantity.value]]
=== BigDecimal - Representing numerical values
`BigDecimal` was chosen as datatype for the `amount` attribute over `float` or `double` because of its arbitraty precision. Moreover, objects of `BigDecimal` are `immutable` and the `BigDecimal` class provides operations for including, but not limited to: arithmetic, rounding, and comparison.

[[modules.quantity.metric]]
=== Metric - What is represented
The composite type `Metric` contains all information pertaining to the unit or metric of the represented object. Examples for units or metrics are: m (meter), s (second), pcs (pieces). For example consider the unit of length "meter": represented by an object of the class `Metric` the symbol would be set to `m` and the name to `meter`. Furthermore, an object of type `Metric` has a description field, to explain the meaning of the metric in detail. For the example of a meter a possible description could be "The meter is the length of the path travelled by light in vacuum during a time interval of 1/299 792 458 of a second.".

[[modules.quantity.rounding]]
=== Rounding
There are many rounding strategies, for money operations and so on. For this case, Salespoint ships with a `RoundingStrategy` interface providing a `round()` method. This implementation of this `RoundingStrategy`, `BasicRoundingStrategy` offers two ways to describe a rounding operation: using the decimal places after (or before) the decimal delimiter and using a rounding step.

[[modules.catalog]]
== Catalog
The `Catalog` interface was designed to manage Products and ProductFeatures in the system. It provides functionality to add, remove, and find Products. Products can be searched by their name or category. Products and ProductFeatures are more closely described in Section <<modules.product>>. The `PersistentCatalog` is an implementation of the `Catalog` interface.

Additionally `PersistentCatalog` provides an `update()`-method to update and merge existing `PersistentProduct`s to the database. The `find()` methods request the database in the form of CriteriaQuerys which will be processed by JPA and results are returned in the form of Iterables. The reason for this is to make returned objects immutable without making it difficult to iterate over these results.

[[modules.accountancy]]
== Accountancy
The accountancy package contains functionality supporting book keeping. `AccountancyEntry` is a representation of an accounting entry. `Accountancy` aggregates AccountancyEntrys. Every `AccountancyEntry` is uniquely identified by an `AccountancyEntryIdentifier` . `AccountancyEntry` extends `AbstractEntity` and serves as persistence entity, while `PersistentAccountancy` implements `Accountancy` and provides transparent access to the JPA layer. `AccountancyEntryIdentifier` is used as primary key attribute, when entities are stored in the database.

By implementing and sub-classing the `Accountancy` interface, the notion of different accounts, as known from double-entry bookkeeping, can be realised.

Payment information also includes a user identifier referencing the buyer, an order identifier referring to the <<modules.catalog>> which was payed, and a <<modules.payment>> describing the money transfer. The attributes are named `userIdentifier` , `orderIdentifier` , and `paymentMethod` respectively.

To create a new account, AccountancyEntry has to be sub-classed. Every object of such a class belongs to the same account. Accessing per-account entries is facilitated by specifiying the desired class type when calling _get()_ or _find()_ methods of Accountancy.

[[modules.payment]]
== Payments

TODO

[[modules.order]]
== Order
An `Order` can be considered as a sheet of paper which basically consists of lines, each representing an ordered product. An order can be uniquely identified by an `OrderIdentifier`. Every product of an order is stored in a separate `OrderLine`. An `OrderLine` in turn is uniquely identified by an `OrderLineIdentifier`. An `OrderLine` contains all information to identify a `ProductInstance` (see Section <<modules.product>> ). A `ProductInstance` is identified by a `ProductIdentifier` , and an optional set of `ProductFeature` s.

A `ChargeLine` represents additional costs or discounts and can be applied to an `OrderLine` or an `Order`.

NOTE: For example, `ChargeLine`s can be used to handle special taxes or handling fees.

A `ChargeLine` is uniquely identified by a `ChargeLineIdentifier` .

=== Order status lifecycle
`Orders` are lifecycle-objects. The lifecycle covers four states which are defined by enumeration type `OrderStatus`. The lifecycle state cannot be arbitrarily changed, but follows a fixed scheme.

.Example for OrderStatus as field `orderStatus` in the class `Order`
[source, java, indent=0]
----
include::{source-base}/order/Order.java[tags=orderStatus]
----

State transistions are automatically carried out when certain methods are called on an `Order` object, for example `cancelOrder()`.

A `Order` can only be modified in state `OPEN`. `PAID` , `CANCELLED` and `COMPLETED` `Order` s are immutable. Calling the `payOrder()` method changes the state to `PAID` ,makes the `Order` immutable and creates an `ProductPaymentEntry` object. Ordered objects will only be removed from inventory when the `completeOrder()` method is called. `COMPLETED` is one of the final states and it is not possible to change the state of such orders.

Completing an order causes product instances to be removed from the inventory. Because product instances may not be present anymore in the inventory, or their number may not be suffice to fulfill an order, completing an order requires special attention. To handle these situations, the `OrderCompletionResult` interface was introduced. First of all, these `OrderCompletionStatus` are possible:

* `SUCCESSFUL` -- The order was completed successfully, and all products were removed from the inventory.
* `FAILED` -- An error from which recovery is impossible occured.

The `OrderManager` aggregates `Order`s. The implementation of `OrderManager` interface, `PersistentOrderManager`, is used to persist, update, find and remove orders to/from the database. In `Order` aggregated objects, like `OrderLine`s and `ChargeLine`s will also be persisted, updated or removed with the `Order` object.

[[modules.business-time]]
== Business time

[[modules.technical-apis]]
== Technical APIs

Besides the business modules, Salespoint containes a few <<glossary.spi,SPIs>> that can be used to extend the functionality of the core framework. These SPIs usually exist to make repeated use-cases easier to implement and free you from writing too much boilerplate code.

[[modules.technical-apis.data-initializer]]
=== DataInitializer

Every application should be tested, so an easy way is, to use test data. So for this goal a recommend solution is, to load on every start of the application a bundle of test data into your system. As shown in the Videoshop project, a `DataInitializer` class is registered and creates a lot of data and finally adds this data to the application. For that purpose the Salespoint has an Interface `org.salespointframework.DataInitializer`, which can be used.

= Appendix

[appendix]
== FAQ

[qanda]
Why do I see warning log statements about database tables not being accessible at startup?::
  This is due to a bug in Hibernate in combination with HSQLDB and constraints in databases. Hibernate tries to drop those on application startup but fails to as the (in-memory database) is empty. See https://hibernate.atlassian.net/browse/HHH-9038[this bug report] for reference.

[[glossary]]
[appendix, glossary]
== Glossary

[[glossary.dependency-injection]]
Dependency injection::
   Dependency injection is a software design pattern that implements inversion of control and allows a program design to follow the dependency inversion principle. The term was coined by Martin Fowler. See http://en.wikipedia.org/wiki/Dependency_injection[Wikipedia].

[[glossary.spi]]
SPI::
   Service Provider Interface -- interfaces to be implemented to extend the functionality of the core framework. See http://en.wikipedia.org/wiki/Service_provider_interface[Wikipedia] for details.

[[bibliography]]
[appendix, bibliography]
== Bibliography
- [[[ddd]]] Eric Evans. Domain-Driven Design: Tackling Complexity in the Heart of Software. Prentice Hall. 2003
- [[[epam]]] Jim Arlow, Ila Neustadt. Enterprise Patterns and MDA: Building Better Software with Archetype Patterns and UML. Addison-Wesley. 2004.
- [[[di]]] Martin Fowler. Inversion of Control Containers and the Dependency Injection pattern. 2004. http://www.martinfowler.com/articles/injection.html

[appendix]
== Asciidoc template

Some random snippets to show how Asciidoc is used. For more examples see the http://asciidoctor.org/docs/user-manual[user manual].

.Example for code snippets
====
[source, java]
----
class SomeClass { }
----
====

.Example for code included from the sources
====
[source, java]
----
include::{source-base-test}/AbstractIntegrationTests.java[tags=testBase]
----
====