= Salespoint Framework

image:https://travis-ci.org/st-tu-dresden/salespoint.svg?branch=master["Build Status", link="https://travis-ci.org/st-tu-dresden/salespoint"]

== Prerequisites

- Java 13
- Git
- Maven 3.x

== Building the project

.Building the project
[source, bash]
----
$ git clone https://github.com/st-tu-dresden/salespoint
$ cd salespoint
$ mvn clean install
----

== Documentation

The reference documentation is written in Asciidoc and built using Asciidoctor. The main documentation source file is located in `src/main/asciidoc`.

To build the reference documentation simply run `mvn -Pdocs package` on the command line. This generates the following HTML files:

* the Salespoint website in `target/generated-docs/index.html`.
* the Salespoint reference in `target/generated-docs/salespoint-reference.html`.

== Deployment

To deploy artifacts to the salespoint repository, simply run `mvn clean deploy`. This requires your `settings.xml` (located in `~/.m2` ) to contain a server definition with the credentials to access the Salespoint server via SFTP:

[source, xml]
----
<server>
  <id>salespoint</id>
  <username>…</username>
  <password>…</password>
</server>
----

To deploy the website and reference documentation, run `mvn -Pdocs site:deploy`.

== Release

1. Make sure all tickets are closed, except the release one.
2. Tweak `ChangelogCreator` (in `src/test/java`) to point to the milestone to be released. Run the creator. Copy console output into `src/main/asciidoc/site/changelog.adoc`.
3. Commit as `#?? - Prepare release $version.`.
4. Run `mvn release:prepare`.
5. Edit commits to match commit message format, re-create tag.
6. Push changes & tag.
7. Check out tag.
8. Run `mvn clean deploy -Prelease -DskipTests && mvn site:deploy -Pdocs`.
