= Salespoint Framework
Paul Henke, Andreas Zaschka, Oliver Drotbohm
:revdate: {localdate}

Salespoint is a Java-based application framework to develop point of sales (PoS) applications using Spring Framework and Spring Boot. It consists of a variety of business modules that allows users to implement sophisticated web applications on top of them.

toc::[]

The framework fundamentally consists of:

* 6 business modules - accountancy, inventory, catalog, orders, business time and user accounts.
* Domain types (entities and value objects) as well as Spring based repository and service implementations to provide Java APIs to be extended by (web) application developers.
* Core Spring application configuration classes to bootstrap the application using Spring Boot.

Read more details about Salespoint in the link:salespoint-reference.html[reference documentation].

[[resources]]
== Resources

[[resources.latest]]
=== Latest release version - 7.4.0
* link:salespoint-reference.html[Reference documentation]
* link:api[JavaDoc]
* link:changelog.html[Changelog]
* Maven repository declaration:
+
[source, xml]
----
<repository>
  <id>salespoint-framework</id> <!-- Name doesn't matter -->
  <url>http://www.st.inf.tu-dresden.de/SalesPoint/repository</url>
</repository>
----
* Maven dependency:
+
[source, xml]
----
<dependency>
  <groupId>de.tudresden.inf.st</groupId>
  <artifactId>salespoint-framework</artifactId>
  <version>7.4.0</version>
</dependency>
----

[[resources.development]]
=== Current development snapshot - 7.4.x / 7.5 snapshots
* link:dev/salespoint-reference.html[Reference documentation]
* link:dev/api[JavaDoc]
* Maven repository declaration:
+
[source, xml]
----
<repository>
  <id>salespoint-framework</id> <!-- Name doesn't matter -->
  <url>http://www.st.inf.tu-dresden.de/SalesPoint/repository</url>
</repository>
----
* Maven dependency:
+
[source, xml]
----
<dependency>
  <groupId>de.tudresden.inf.st</groupId>
  <artifactId>salespoint-framework</artifactId>
  <version>7.4.1-SNAPSHOT</version>
</dependency>
----

[[resources.sample-projects]]
=== Sample projects

[[resources.sample-projects.videoshop]]
==== Videoshop
The primary sample project for Salespoint applications is the https://github.com/st-tu-dresden/videoshop[Videoshop]. It's a web application to manage Blu-ray discs and DVD. It uses Salespoint's order, catalog, inventory and user management modules and is a web application centered around Spring Boot, Spring MVC and Thymeleaf.

[[resources.sample-projects.guestbook]]
==== Guestbook
If you want to familiarize your self with the technology stack that Salespoint link:salespoint-reference.html#stack[is built upon], check out the https://github.com/st-tu-dresden/guestbook[Guestbook project]. It's a simple guestbook web application built solely on top og Spring Boot, Spring MVC, Spring Data JPA as well as Thymeleaf and Bootstrap.

[[appendix]]
= Appendix

[appendix]
[[archive]]
== Archive

* Version 7.3 - link:v7.3/salespoint-reference.html[Reference], link:v7.3/api[JavaDoc]
* Version 7.2 - link:v7.2/salespoint-reference.html[Reference], link:v7.2/api[JavaDoc]
* Version 7.1 - link:v7.1/salespoint-reference.html[Reference], link:v7.1/api[JavaDoc]
* Version 7.0 - link:v7.0/salespoint-reference.html[Reference], link:v7.0/api[JavaDoc]
* Version 6.4 - link:v6.4/salespoint-reference.html[Reference], link:v6.4/api[JavaDoc]
* Version 6.3 - link:v6.3/salespoint-reference.html[Reference], link:v6.3/api[JavaDoc]
* Version 6.2 - link:v6.2/salespoint-reference.html[Reference], link:v6.2/api[JavaDoc]
* Version 6.1 - link:v6.1/salespoint-reference.html[Reference], link:v6.1/api[JavaDoc]
* Version 6.0 - link:v6.0/salespoint-reference.html[Reference], link:v6.0/api[JavaDoc]
* link:v5.0/wiki[Version 5.0]
* link:v4.0[Version 4.0]
* link:v3.3[Version 3.3]
* link:v3.2[Version 3.2]
* link:v3.1[Version 3.1]
* link:v3.0[Version 3.0]
